name: Enforce Feature Branch Merge

on:
  pull_request:
    branches:
      - main # This workflow only runs when a PR targets the 'main' branch
    types: [opened, reopened, synchronize] # Trigger on PR creation and updates

jobs:
  check_source_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch name
        id: get_branch_name
        run: echo "::set-output name=branch::${{ github.head_ref }}"

      - name: Validate branch starts with 'features/'
        run: |
          SOURCE_BRANCH="${{ steps.get_branch_name.outputs.branch }}"
          echo "Checking source branch: $SOURCE_BRANCH"
          if [[ "$SOURCE_BRANCH" =~ ^features/ ]]; then
            echo "Success: Source branch '$SOURCE_BRANCH' follows the 'features/' naming convention."
          else
            echo "Failure: Source branch '$SOURCE_BRANCH' does NOT follow the 'features/' naming convention."
            echo "Only branches starting with 'features/' can be merged into 'main'."
            exit 1 # This will cause the GitHub Action to fail
          fi
